# Generated by Django 5.0.7 on 2025-06-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('AKINCI', 'AKINCI'), ('KIZILELMA', 'KIZILELMA')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WING', 'Wing Team'), ('FUSELAGE', 'Fuselage Team'), ('TAIL', 'Tail Team'), ('AVIONICS', 'Avionics Team'), ('ASSEMBLY', 'Assembly Team')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('part_type', models.CharField(choices=[('WING', 'Wing'), ('FUSELAGE', 'Fuselage'), ('TAIL', 'Tail'), ('AVIONICS', 'Avionics')], max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('plane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.plane')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlanePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=1)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part')),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.plane')),
            ],
            options={
                'unique_together': {('plane', 'part')},
            },
        ),
        migrations.AddField(
            model_name='plane',
            name='parts',
            field=models.ManyToManyField(related_name='planes', through='production.PlanePart', to='production.part'),
        ),
    ]
