# Generated by Django 5.0.7 on 2025-06-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assembled', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('INCOMPLETE', 'Incomplete')], default='INCOMPLETE', max_length=20)),
                ('plane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.plane')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=1)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assembly.assembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.part')),
            ],
        ),
    ]
